
# Uncomment this line to define a global platform for your project
# platform :ios, ’10.0’

def pod_import
    source 'https://github.com/forcedotcom/SalesforceMobileSDK-iOS-Specs.git' # need to be first
    source 'https://github.com/CocoaPods/Specs.git'
    
    use_frameworks!

    pod 'SalesforceAnalytics','=6.2.0’
    pod 'SmartStore','=6.2.0’
    pod 'SmartSync','=6.2.0’
    pod 'SalesforceSDKCore','=6.2.0’
    pod 'FMDB', :git => 'https://github.com/forcedotcom/fmdb', :branch => '2.7.2_xcode9'

end


target 'TestApp' do
    pod_import
end

